= Numeric overflow

//tag::abstract[]

Numeric overflow in Java is commonly overlooked. 
This vulnerability appears where the range of
numeric is not being validated.

//end::abstract[]

For example, 
Integer in Java is 32 bits, therefore it ranges
between -/+2,147,483,647.

If a given value is bigger or smaller than Integer
range, the variable overflows and turn to a negative
or positive numbers respectively.

This vulnerability can cause logic bypass often
result in serious impact. Think how in a banking
application a daily transaction threshold can get
passed by using this vulnerability?

This vulnerabilities affects all numeric types
that do no use dynamic memory allocation.

//tag::lab[]

== Lab 9

=== Task 0

Clone this repository.
Install `docker` and `make` on your system.

. Build the program: `make build`.
. Run it: `make run`.
. Run unit tests: `make test`.
. Run security tests: `make securitytest`.

[NOTE]
--
There are no security tests. You will write them later on.
--

=== Task 1

There is a bug in the code.
Run the project and give it an amount.
Review the program code and try to find the bug.

=== Task 2

Perform both run-time and static analysis to test for this vulnerability.
See if you can figure out a way to use the bug to bypass approval for an amount
that should otherwise require approval.

You can try to use the test data that has been shown in the lecture slides (Slide number 37).

=== Task 3

Review `test/java/appSpec.java` and see how the tests work.
Your task is to write tests to test for edge cases that can trigger the vulnerability.

You should write the tests `test/java/appSecuritySpec.java` file. Use the comments as a guide, and feel free to write some extra tests if you can think of more edge cases.

[IMPORTANT]
--
The security tests you write should fail. You do not have to patch the program to make the tests pass (and subsequently fix the vulnerability) in this lab.
--

[NOTE]
--
Use the existing test code in `test/java/appSpec.java` as a guide. The libraries required for you are also already imported in `test/java/appSecuritySpec.java`. Google is your friend.
--

== Lab 10

[IMPORTANT]
--
Make sure you've completed Tasks 1-3 before attempting the remaining tasks!
--

For this lab, you should create a new branch for each task. If you're unfamiliar with how branching works in git, https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging[have a read of this].

=== Task 1

Patch the vulnerability in the program by applying the pre-condition check. You can use either a safe addition implementation, or a safe subtraction implementation, whichever makes sense. You may have to modify your security tests slightly (either just modify them, or remove a few redundant ones) depending on how you choose to write the patch.

=== Task 2

Patch the vulnerability in the program by applying an upcasting check. You may have to modify your security tests slightly (either just modify them, or remove a few redundant ones) depending on how you choose to write the patch.

=== Task 3

Patch the vulnerability in the program by using your own custom type. You can write a wrapper around a built-in type (such as the BigInteger class for example). If you finish this and still have more time (and are just curious in general), then implement your custom type from scratch without depending on any built-in types (except for the usual ones of course, i.e Strings, integers, longs, etc are all allowed). You will most definitely have to modify your security tests when you write this patch.

=== Task 4

Depending on how you've completed the previous three tasks, it may make sense to combine them all together (in some fashion). In this task, you should do just that: combine the patches from the previous three tasks into one. You will probably have to make modifications to your security tests again.

== References

* OWASP Application Security Verification Standard 4.0, 5.4.3
* CWE 190

//end::references[]

== License

See link:LICENSE[]
